name: pachamama

services:
  front:
    image: "ghcr.io/viktor-titov/demo-front:0.0.2"
    container_name: pachamama-front
    ports:
      - "1234:80"
    restart: unless-stopped
    networks:
      - pachamama-network
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: pachamama-npm
    restart: unless-stopped
    environment:
      TZ: "Australia/Brisbane"
      DB_POSTGRES_HOST: postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: postgres
      DB_POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - pachamama-network
  n8n:
    image: "docker.n8n.io/n8nio/n8n"
    container_name: pachamama-n8n
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5678:5678"
    environment:
      # GENERIC_TIMEZONE: "<YOUR_TIMEZONE>"
      # TZ: "<YOUR_TIMEZONE>"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      N8N_SECURE_COOKIE: false
      N8N_RUNNERS_ENABLED: true
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: pachamama
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      # DB_POSTGRESDB_SCHEMA: <POSTGRES_SCHEMA>
      DB_POSTGRESDB_PASSWORD: password
      WEBHOOK_URL: "https://n8n.nulltomato-demo.ru"
    volumes:
      - "n8n_data:/home/node/.n8n"
    networks:
      - pachamama-network
    
  nocodb: 
    image: "nocodb/nocodb:latest"
    container_name: pachamama-nocodb
    depends_on: 
      postgres: 
        condition: service_healthy
    environment: 
      NC_DB: "pg://postgres:5432?u=postgres&p=password&d=pachamama"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
    networks:
      - pachamama-network
  baserow:
    image: "baserow/baserow:2.1.3"
    container_name: pachamama-baserow
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BASEROW_PUBLIC_URL: https://baserow.nulltomato-demo.ru
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: pachamama
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    volumes:
      - "baserow_data:/baserow/data"
    networks:
      - pachamama-network
  postgres:
    image: postgres:16.6
    container_name: pachamama-postgres
    environment: 
      POSTGRES_DB: pachamama
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    healthcheck:
      # test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d pachamama']
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    volumes: 
      - "db_data:/var/lib/postgresql/data"
    networks:
      - pachamama-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pachamama-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pachamama-network
volumes: 
  db_data:
  nc_data:
  pgadmin_data:
  n8n_data:
  npm_data:
  npm_letsencrypt:
  baserow_data:
networks:
  pachamama-network:
    driver: bridge